#!/bin/sh
code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension Boto3typed.boto3-ide
code --install-extension charliermarsh.ruff
code --install-extension codezombiech.gitignore
code --install-extension dorzey.vscode-sqlfluff
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension github.vscode-github-actions
code --install-extension Gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension kennylong.kubernetes-yaml-formatter
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.mypy-type-checker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension samuelcolvin.jinjahtml
code --install-extension tamasfe.even-better-toml
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension richie5um2.vscode-sort-json
